version: "3.7"
services:
  db:
    env_file:
      - .env
    container_name: db
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - flask-app-db:/var/lib/postgresql/data
    ports:
      - "5401:5432"
  app:
    container_name: loan
    env_file:
      - .env
    restart: always
    build:
      context: .
      dockerfile: project/docker/Dockerfile
    ports:
      - 3200:3200
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  flask-app-db:
    name: flask-app-db
